name: ft_transcendence
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    container_name: database
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # networks:
    #   - ft_transcendence

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    # environment:
    #   - PORT=${PORT}
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    # networks:
    #   - ft_transcendence

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    # networks:
    #   - ft_transcendence

    # networks:
    #   ft_transcendence:
    #     name: ft_transcendence
